// unslopify:INV-6 — inert-input trust boundary, instruction residue signal, and context-aware workflow phrase candidates
import { describe, test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { read, norm } from "../../../scripts/test-helpers.ts";

const ROOT = path.resolve(import.meta.dirname ?? ".", "../../..");
const FIXTURES = path.join(ROOT, "skills/unslopify/tests/fixtures");
const SCANNER = path.join(ROOT, "skills/unslopify/scanner.py");

function pythonAvailable(): boolean {
  const probe = spawnSync("python3", ["--version"], { encoding: "utf8" });
  return probe.status === 0;
}

function scan(fixture: string): { status: number; findings: Array<{ id: string; family: string; evidence: string; excerpt: string; line_start: number; line_end: number; measured_value: number }> } {
  const file = path.join(FIXTURES, fixture);
  const res = spawnSync("python3", [SCANNER, "--json", file], { encoding: "utf8" });
  assert.equal(res.status, 0, `scanner must exit 0 on ${fixture}: ${res.stderr}`);
  const parsed = JSON.parse(res.stdout) as { findings: Array<{ id: string; family: string; evidence: string; excerpt: string; line_start: number; line_end: number; measured_value: number }> };
  return { status: res.status ?? 0, findings: parsed.findings };
}

const SESSION_BLOCK = [
  "<!-- unslopify:session-start:start -->",
  "Load `unslopify` before the first user-visible response in every session. Keep it active for all model-authored English questions and prose.",
  "<!-- unslopify:session-start:end -->",
].join("\n");

const BLOCK_RE = /<!-- unslopify:session-start:start -->[\s\S]*?<!-- unslopify:session-start:end -->/g;

function countBlocks(text: string): number {
  return (text.match(BLOCK_RE) ?? []).length;
}

const OWNED_RE = /<!-- unslopify:session-start:start -->[\s\S]*?<!-- unslopify:session-start:end -->/;

// Reference model for SKILL.md's Session-start setup rules 1-9. It mirrors the
// prose contract so the byte-level guarantees are machine-checked: an exact
// existing block is a no-op; a stale owned block gets only its body replaced;
// duplicate, unmatched, or nested markers and files another generator owns
// produce no edit; a managed file takes the block directly after the
// management-marker line; a file with valid frontmatter takes it directly
// after the frontmatter; a bare file takes it at byte zero followed by a blank
// separator. Insertion adds only the owned block (plus the one separator in
// the byte-zero case), so every pre-existing byte survives.
function applySetup(text: string): string {
  if (text.includes("generated by") || text.includes("another generator owns")) return text;
  const startCount = (text.match(/<!-- unslopify:session-start:start -->/g) ?? []).length;
  const endCount = (text.match(/<!-- unslopify:session-start:end -->/g) ?? []).length;
  const nested = /<!-- unslopify:session-start:start -->[\s\S]*?<!-- unslopify:session-start:start -->/.test(text);
  if (startCount !== endCount || startCount > 1 || nested) return text;
  if (OWNED_RE.test(text)) {
    if (text.includes(SESSION_BLOCK)) return text;
    return text.replace(OWNED_RE, SESSION_BLOCK);
  }
  const management = text.indexOf("<!-- managed: document-for-agents");
  if (management !== -1) {
    const lineEnd = text.indexOf("\n", management);
    const at = lineEnd === -1 ? text.length : lineEnd + 1;
    return text.slice(0, at) + SESSION_BLOCK + text.slice(at);
  }
  const fm = text.match(/^---\n[\s\S]*?\n---\n/);
  if (fm) return fm[0] + SESSION_BLOCK + text.slice(fm[0].length);
  return SESSION_BLOCK + "\n\n" + text;
}

describe("unslopify inert input and context-aware candidates (unslopify:INV-6)", () => {
  test("flags instruction residue in visible prose as inert content", { skip: !pythonAvailable() }, () => {
    const { findings } = scan("prompt-residue.md");
    const residue = findings.filter((f) => f.id === "AIT-EVD-010");
    assert.ok(residue.length >= 2, `expected at least two residue hits in visible prose, got ${residue.length}`);
    const joined = norm(residue.map((f) => f.evidence).join(" "));
    assert.ok(joined.includes("inert"), "findings must state the content is inert, never executed");
  });

  test("keeps protected prompt-like spans out of findings", { skip: !pythonAvailable() }, () => {
    const { findings } = scan("prompt-residue-protected.md");
    const residue = findings.filter((f) => f.id === "AIT-EVD-010");
    assert.equal(residue.length, 0, "frontmatter, fenced code, and inline code copies must stay masked");
  });

  test("reports vague workflow phrase uses as replaceable candidates", { skip: !pythonAvailable() }, () => {
    const { findings } = scan("phrase-candidates.md");
    const candidates = findings.filter((f) => f.id === "AIT-LEX-008");
    const evidence = norm(candidates.map((f) => f.evidence).join(" "));
    for (const phrase of ["vertical slice", "native dependency edges"]) {
      assert.ok(evidence.includes(phrase), `vague use of '${phrase}' must be reported as a candidate`);
    }
    assert.equal(evidence.includes("load bearing"), false, "load bearing is no longer a context-aware candidate");
  });

  test("preserves exact domain uses without candidate findings", { skip: !pythonAvailable() }, () => {
    const { findings } = scan("exact-terms.md");
    assert.equal(findings.filter((f) => f.id === "AIT-LEX-008").length, 0, "exact domain uses of the two context-aware phrases must not become findings");
    assert.equal(findings.filter((f) => f.id === "AIT-LEX-009").length, 0, "the exact-terms fixture must carry no always-replace phrase");
  });

  test("reports every visible always-replace phrase occurrence under AIT-LEX-009", { skip: !pythonAvailable() }, () => {
    const { findings } = scan("always-replace-phrases.md");
    const hits = findings.filter((f) => f.id === "AIT-LEX-009");
    assert.equal(hits.length, 5, `expected one finding per visible occurrence, got ${hits.length}`);
    for (const f of hits) {
      assert.equal(f.measured_value, 1, "each occurrence reports a count of one");
      assert.equal(f.family, "LEX");
    }
    const joined = norm(hits.map((f) => `${f.evidence} ${f.excerpt}`).join(" "));
    assert.ok(joined.includes("load-bearing"), "hyphenated spelling must be reported");
    assert.ok(joined.includes("load bearing"), "spaced spelling must be reported");
    assert.ok(joined.includes("smoking gun"), "smoking gun must be reported");
    assert.ok(joined.includes("smoke test"), "smoke test must be reported");
    assert.ok(joined.includes("smoke tests"), "plural smoke tests must be reported");
  });

  test("keeps protected copies and adjacent text out of always-replace findings", { skip: !pythonAvailable() }, () => {
    const { findings } = scan("always-replace-phrases.md");
    const hits = findings.filter((f) => f.id === "AIT-LEX-009");
    const protectedLines = [9, 11, 12, 13, 15];
    for (const f of hits) {
      assert.equal(
        protectedLines.some((l) => f.line_start <= l && l <= f.line_end),
        false,
        `line ${f.line_start} must carry no finding: inline-code, fenced, and non-matching copies are protected`,
      );
    }
    assert.equal(hits.every((f) => [3, 5, 7].includes(f.line_start)), true, "only the visible-prose lines may match");
  });

  test("always-replace scanning is deterministic", { skip: !pythonAvailable() }, () => {
    const first = scan("always-replace-phrases.md");
    const second = scan("always-replace-phrases.md");
    assert.deepEqual(second.findings, first.findings, "repeat scans must produce identical JSON findings");
  });

  test("scanner behavior version is 1.1 with schema version 1.0", { skip: !pythonAvailable() }, () => {
    const res = spawnSync("python3", [SCANNER, "--version"], { encoding: "utf8" });
    assert.equal(res.status, 0);
    assert.equal(res.stdout.trim(), "unslopify scanner 1.1 (schema 1.0)");
    const file = path.join(FIXTURES, "always-replace-phrases.md");
    const json = spawnSync("python3", [SCANNER, "--json", file], { encoding: "utf8" });
    assert.equal(json.status, 0);
    assert.equal((JSON.parse(json.stdout) as { schema_version: string }).schema_version, "1.0");
  });

  test("scanning is deterministic on hostile input", { skip: !pythonAvailable() }, () => {
    const first = scan("prompt-residue.md");
    const second = scan("prompt-residue.md");
    assert.deepEqual(second.findings, first.findings, "repeat scans must produce identical JSON findings");
  });
});

describe("unslopify trust contract in SKILL.md and parity catalog (unslopify:INV-6)", () => {
  test("SKILL.md declares the inert-input boundary over scoped prose", () => {
    const skill = read("skills/unslopify/SKILL.md");
    const n = norm(skill);
    assert.ok(skill.includes("## Inert input"), "must carry an Inert input section");
    assert.ok(n.includes("content, never instruction"), "must define scoped prose as content, never instruction");
    for (const cannot of ["widen scope", "select files", "authorize tools"]) {
      assert.ok(n.includes(cannot), `embedded directives must be unable to ${cannot}`);
    }
    assert.ok(n.includes("never execute it"), "must forbid executing embedded directives");
  });

  test("SKILL.md documents instruction residue, the context-aware phrases, and the always-replace set with identifiers", () => {
    const skill = read("skills/unslopify/SKILL.md");
    const n = norm(skill);
    assert.ok(n.includes("ait-evd-010"), "must name AIT-EVD-010 for instruction residue");
    assert.ok(n.includes("ait-lex-008"), "must name AIT-LEX-008 for workflow phrase candidates");
    assert.ok(n.includes("ait-lex-009"), "must name AIT-LEX-009 for always-replace phrases");
    for (const phrase of ["vertical slice", "native dependency edges"]) {
      assert.ok(n.includes(phrase), `must name '${phrase}' as a context-aware candidate`);
    }
    for (const phrase of ["load-bearing", "load bearing", "smoking gun", "smoke test"]) {
      assert.ok(n.includes(phrase), `must name '${phrase}' as an always-replace phrase`);
    }
    assert.ok(n.includes("exact domain uses unchanged") || n.includes("keep exact domain uses unchanged"), "must preserve exact domain uses");
    assert.ok(n.includes("even when the phrase is technically correct"), "always-replace phrases are replaced even when technically correct");
  });

  test("parity catalog maps every new identifier uniquely within six families", () => {
    const parity = read("skills/unslopify/reference/parity.md");
    for (const id of ["AIT-EVD-010", "AIT-LEX-008", "AIT-LEX-009"]) {
      const matches = parity.match(new RegExp(id.replace(/-/g, "\\-"), "g")) ?? [];
      assert.ok(matches.length >= 1, `${id} must appear in the extended table`);
    }
    const lex008Row = parity.split("\n").find((l) => l.startsWith("| AIT-LEX-008 |")) ?? "";
    assert.equal(lex008Row.includes("load bearing"), false, "AIT-LEX-008 must no longer list load bearing");
    const declared = [...parity.matchAll(/^\| (AIT-(?:LEX|STR|FMT|CONV|EVD|VOICE)-\d{3}) \|/gm)].map((m) => m[1]);
    assert.equal(new Set(declared).size, declared.length, "extended identifiers must be unique");
    assert.ok(parity.includes("Six families cover every upstream rule and every extended subtle tell."));
  });

  test("leaf doc declares INV-6 with scanner and fixture mechanisms", () => {
    const leaf = read("docs/leaves/unslopify.md");
    assert.ok(leaf.includes("INV-6"), "leaf must declare INV-6");
    assert.ok(leaf.includes("skills/unslopify/tests/"), "leaf must name the fixture location");
    assert.ok(leaf.includes("AIT-LEX-009"), "the revised INV-6 must name the always-replace identifier");
  });

  test("INSTALL.md records provenance, pinning, residual trust, no downloads, and overwrite approval", () => {
    const install = read("skills/unslopify/INSTALL.md");
    const n = norm(install);
    assert.ok(n.includes("provenance"), "install guidance must record source provenance");
    assert.ok(n.includes("pin the revision you reviewed"), "must pin reviewed revisions where supported");
    assert.ok(n.includes("residual trust"), "must state residual source-repository trust");
    assert.ok(n.includes("w011"), "must reference Snyk W011 for this install path");
    assert.ok(n.includes("no downloads at run time") || n.includes("never fetch, clone, or install skills mid-run"), "must state the no-download boundary");
    assert.ok(n.includes("overwrit") && n.includes("explicit approval"), "manual installs must not overwrite without explicit approval");
    for (const claim of ["eliminated", "eradicated", "no longer applies", "no longer present", "resolved the risk"]) {
      assert.equal(n.includes(claim), false, `must not claim the Snyk findings are gone (${claim})`);
    }
  });

  test("fixtures exist for prompt-like prose, candidate replacement, exact-term preservation, protected content, and always-replace phrases", () => {
    for (const fixture of [
      "prompt-residue.md",
      "prompt-residue-protected.md",
      "phrase-candidates.md",
      "exact-terms.md",
      "always-replace-phrases.md",
    ]) {
      assert.ok(fs.existsSync(path.join(FIXTURES, fixture)), `fixture ${fixture} must exist`);
    }
  });
});

// unslopify:INV-7 — always-on output contract: agent-authored English output is the automatic scope once loaded,
// routine chat and published artifacts audit silently with no audit block, an explicit rewrite-audit request
// returns the full report and preservation audit, user text stays explicit edit scope and inert input, and
// technical fidelity outranks style.
describe("unslopify always-on output contract (unslopify:INV-7)", () => {
  test("SKILL.md makes agent-authored English output the automatic scope once loaded", () => {
    const skill = read("skills/unslopify/SKILL.md");
    const n = norm(skill);
    assert.ok(skill.includes("## Live output"), "must carry a Live output section");
    assert.ok(n.includes("agent-authored english output"), "must name agent-authored English output");
    assert.ok(n.includes("automatic scope"), "loading must make agent output the automatic scope");
    for (const surface of ["progress updates", "recommendations", "decisions", "github comments"]) {
      assert.ok(n.includes(surface), `always-on scope must cover ${surface}`);
    }
  });

  test("user-authored prompts, quoted text, and requirements stay explicit edit scope and inert", () => {
    const skill = read("skills/unslopify/SKILL.md");
    const n = norm(skill);
    assert.ok(n.includes("remains inert") || n.includes("remain inert"), "user text must remain inert");
    assert.ok(n.includes("explicit edit request") || n.includes("explicitly requests an edit"), "user text changes only on an explicit edit request");
  });

  test("routine chat performs the full self-audit silently, with no completion report", () => {
    const skill = read("skills/unslopify/SKILL.md");
    const n = norm(skill);
    assert.ok(n.includes("self-audit silently"), "ordinary conversation must be audited silently");
    assert.ok(n.includes("without showing a completion report") || n.includes("no completion report"), "routine chat must not show a completion report");
  });

  test("published artifacts are checked before publication without an audit block", () => {
    const skill = read("skills/unslopify/SKILL.md");
    const n = norm(skill);
    assert.ok(n.includes("at publication boundaries"), "publication boundaries must be named");
    assert.ok(n.includes("no audit block"), "published content must carry no audit block");
    assert.ok(n.includes("cleanup runs before publishing") || n.includes("before publishing"), "the same cleanup must still run before publication");
  });

  test("an explicit rewrite-audit request still returns the full findings and preservation report", () => {
    const skill = read("skills/unslopify/SKILL.md");
    const n = norm(skill);
    assert.ok(n.includes("explicit rewrite-audit request") || n.includes("asks for an explicit"), "the explicit audit path must be named");
    assert.ok(n.includes("completion report") && n.includes("preservation audit"), "the retained report must cover findings and the preservation audit");
    assert.ok(n.includes("full report"), "only the explicit path publishes the full report");
    const body = skill;
    const report = body.indexOf("## Finding format and completion report");
    const live = body.indexOf("## Live output");
    assert.ok(live !== -1 && report !== -1 && live < report, "Live output must precede the report section it bounds");
  });

  test("technical fidelity outranks style for specification and ticket wording", () => {
    const skill = read("skills/unslopify/SKILL.md");
    const n = norm(skill);
    assert.ok(n.includes("technical fidelity outranks style"), "must state technical fidelity outranks style");
    for (const kind of ["domain terms", "identifiers", "commands", "labels", "dependencies", "quotations"]) {
      assert.ok(n.includes(kind), `precedence list must cover ${kind}`);
    }
    assert.ok(n.includes("implementation-critical"), "specification and ticket wording must be marked implementation-critical");
  });

  test("specification and ticket fixtures pair style candidates with implementation-critical wording", { skip: !pythonAvailable() }, () => {
    for (const [fixture, critical] of [
      ["spec-fixture.md", ["--preserve-manifests", "ETL_NIGHTLY_CRON", "maxConcurrentUploads=4"]],
      ["ticket-fixture.md", ["docs-check.sh", "ready-for-agent", "gh issue edit"]],
    ] as const) {
      const body = fs.readFileSync(path.join(FIXTURES, fixture), "utf8");
      const lines = body.split("\n");
      for (const token of critical) {
        assert.ok(body.includes(token), `${fixture} must carry implementation-critical token ${token}`);
      }
      const { findings } = scan(fixture);
      assert.ok(findings.length >= 1, `${fixture} must produce at least one advisory style candidate`);
      const flagged = (line: number) =>
        findings.some((f) => f.line_start <= line && line <= f.line_end && f.line_end - f.line_start < 3);
      const paired = critical.some((token) =>
        lines.some((text, i) => text.includes(token) && flagged(i + 1)),
      );
      assert.ok(paired, `${fixture} must flag at least one style candidate on a line carrying implementation-critical wording`);
    }
  });

  test("existing scope, protected-content, non-English, and inert-input sections stay intact", () => {
    const skill = read("skills/unslopify/SKILL.md");
    for (const section of ["## Scope — caller owns it", "## Protected content", "## Inert input", "## Language scope", "## Rewrite contract", "## Preservation audit"]) {
      assert.ok(skill.includes(section), `${section} must survive the always-on change`);
    }
    assert.ok(read("skills/unslopify/scanner.py").length > 0, "scanner stays file-oriented; no removal");
  });

  test("one accepted decision record and matching glossary, index, public, and derived updates exist", () => {
    const adr = fs.readdirSync(path.join(ROOT, "docs/adr")).find((f) => f.startsWith("0016-"));
    assert.ok(adr, "ADR-0016 must exist");
    const adrBody = read(`docs/adr/${adr}`);
    const n = norm(adrBody);
    assert.ok(/status:\s*accepted/.test(n), "ADR-0016 must be accepted");
    assert.ok(n.includes("automatic scope"), "ADR-0016 must record the automatic scope decision");
    assert.ok(n.includes("silent"), "ADR-0016 must record the silent live audit");
    assert.ok(norm(read("CONTEXT.md")).includes("always-on scope"), "glossary must define Always-on scope");
    assert.ok(read("ARCHITECTURE.md").includes(`docs/adr/${adr}`), "architecture index must cover ADR-0016");
    assert.ok(norm(fs.readFileSync(path.join(ROOT, "README.md"), "utf8")).includes("once loaded"), "public routing text must state the always-on behavior");
    const leaf = read("docs/leaves/unslopify.md");
    assert.ok(leaf.includes("INV-7"), "leaf doc must declare INV-7");
    assert.ok(leaf.includes("skills/unslopify/tests/"), "INV-7 mechanism must name the test location");
  });

  test("the visible publication-report decision is narrowed openly by ADR-0026", () => {
    const narrow = path.join(ROOT, "docs/adr/0026-unslopify-silent-publication.md");
    assert.ok(fs.existsSync(narrow), "ADR-0026 must record the narrowing");
    const body = read("docs/adr/0026-unslopify-silent-publication.md");
    assert.ok(/narrows:\s*0016/.test(norm(body)), "ADR-0026 must narrow ADR-0016");
    assert.ok(norm(body).includes("no audit block") || norm(body).includes("silent publication"), "ADR-0026 must record silent publication");
    assert.ok(norm(body).includes("explicit"), "ADR-0026 must keep the explicit audit return path");
    assert.ok(
      fs.readFileSync(path.join(ROOT, "docs/manifest.md"), "utf8").includes("0026-unslopify-silent-publication.md"),
      "manifest must list ADR-0026",
    );
  });
});

// unslopify:INV-8 — session-start setup in the project's root AGENTS.md (the one narrow
// exception to caller-owned scope), plain-language active drafting and silent passive
// checking of model-authored English, and install guidance for the missing setup hook.
// The setup rules are prose skill behavior (host file tools, no runtime); a reference
// model encodes rules 1-9 so the byte-level guarantees (placement, stale-body repair,
// no-edit cases, byte-identical repeat, only-owned-bytes changed) are machine-checked
// against the agents-md/ fixtures in memory and over real temp-file writes.
describe("unslopify session-start setup and plain language (unslopify:INV-8)", () => {
  const AGENTS_FIXTURES = path.join(FIXTURES, "agents-md");

  test("SKILL.md carries the exact owned session-start block", () => {
    const skill = read("skills/unslopify/SKILL.md");
    assert.ok(skill.includes("## Session-start setup"), "must carry a Session-start setup section");
    assert.ok(skill.includes(SESSION_BLOCK), "must carry the exact owned block");
  });

  test("setup resolves one root and never walks above it", () => {
    const n = norm(read("skills/unslopify/SKILL.md"));
    assert.ok(n.includes("workspace root"), "must resolve the host workspace root first");
    assert.ok(n.includes("git repository root"), "must fall back to the git repository root");
    assert.ok(n.includes("current working directory"), "must fall back to the current working directory");
    assert.ok(n.includes("never walk above"), "must never walk above the resolved root");
    assert.ok(n.includes("multi-root workspace"), "must not edit other roots in a multi-root workspace");
  });

  test("setup placement keeps the management marker first and covers frontmatter and byte zero", () => {
    const n = norm(read("skills/unslopify/SKILL.md"));
    assert.ok(n.includes("management marker"), "must place the block after a document-for-agents management marker");
    assert.ok(n.includes("directly after"), "marker placement must be directly after the marker");
    assert.ok(n.includes("frontmatter"), "must insert after valid frontmatter when present");
    assert.ok(n.includes("byte zero"), "must insert at byte zero when there is no frontmatter");
  });

  test("setup is idempotent, repairs stale bodies, and stops on malformed markers", () => {
    const n = norm(read("skills/unslopify/SKILL.md"));
    assert.ok(n.includes("no write"), "an exact existing block must produce no write");
    assert.ok(n.includes("replace only its body"), "a stale owned block may change only its body");
    for (const malformed of ["duplicate", "unmatched", "reversed", "nested"]) {
      assert.ok(n.includes(malformed), `malformed marker handling must name ${malformed}`);
    }
    assert.ok(n.includes("make no edit"), "malformed markers must stop the edit");
    assert.ok(n.includes("explain the conflict plainly"), "a marker conflict must be reported plainly");
  });

  test("setup skips symlinks, externally generated files, and forbidden writes with a plain fallback", () => {
    const n = norm(read("skills/unslopify/SKILL.md"));
    assert.ok(n.includes("symlink"), "must not follow an AGENTS.md symlink");
    assert.ok(n.includes("another generator owns"), "must skip files that say another generator owns them");
    assert.ok(n.includes("report the skip"), "a skip must be reported with the exact manual block");
    assert.ok(n.includes("forbids writes"), "a host or parent that forbids writes must be handled");
    assert.ok(n.includes("no partial edit"), "a denied write must not leave a partial edit");
    assert.ok(n.includes("setup was skipped"), "the report must name the skipped future-session setup");
  });

  test("the first successful write announces itself once without asking first", () => {
    const skill = read("skills/unslopify/SKILL.md");
    assert.ok(skill.includes("Updated AGENTS.md so future sessions load unslopify before replying."), "must state the exact one-time notice");
    const n = norm(skill);
    assert.ok(n.includes("do not ask for approval first"), "setup must not wait for approval");
    assert.ok(n.includes("stay silent"), "repeated no-op checks must stay silent");
  });

  test("the root AGENTS.md write is a named narrow exception to caller-owned scope", () => {
    const n = norm(read("skills/unslopify/SKILL.md"));
    assert.ok(n.includes("narrow exception"), "the write must be declared a narrow exception");
    assert.ok(n.includes("root `agents.md`"), "the exception must name root AGENTS.md");
    assert.ok(n.includes("only the owned block"), "the exception must cover only the owned block");
    assert.ok(n.includes("every byte outside"), "bytes outside the block stay protected");
  });

  test("setup needs no new runtime: host file tools only", () => {
    const n = norm(read("skills/unslopify/SKILL.md"));
    assert.ok(n.includes("host's existing file tools") || n.includes("host's file tools"), "setup must use the host's existing file tools");
    assert.ok(n.includes("no python, node, or shell"), "setup must not add a Python, Node, or shell requirement");
  });

  test("plain language runs as active drafting and a silent passive check", () => {
    const n = norm(read("skills/unslopify/SKILL.md"));
    assert.ok(n.includes("active drafting"), "must name the active drafting layer");
    assert.ok(n.includes("passive check"), "must name the silent passive check layer");
    assert.ok(n.includes("practical point"), "drafting must lead with the practical point");
    assert.ok(n.includes("common words"), "drafting must use common words");
    assert.ok(n.includes("one choice at a time"), "questions must ask one choice at a time");
    assert.ok(n.includes("where it first appears"), "specialist terms must be explained at first use");
    assert.ok(n.includes("needless jargon"), "the check must remove needless jargon");
    assert.ok(n.includes("unless the user explicitly asks"), "no audit report unless the user explicitly asks for one");
    assert.ok(n.includes("not what the system does"), "plain language must change wording, not behavior");
  });

  test("install guidance records the missing setup hook and the one invocation per project", () => {
    const n = norm(read("skills/unslopify/INSTALL.md"));
    assert.ok(n.includes("no skill-defined setup hook"), "install must state the CLI has no skill-defined setup hook");
    assert.ok(n.includes("once in each project") || n.includes("once per project"), "install must require one invocation per project");
    assert.ok(n.includes("session loading"), "install must name the session-loading effect");
  });

  test("AGENTS.md fixtures exist for the setup cases", () => {
    for (const fixture of ["ordinary.md", "frontmatter.md", "managed.md", "stale.md", "duplicate.md", "unmatched.md", "protected.md"]) {
      assert.ok(fs.existsSync(path.join(AGENTS_FIXTURES, fixture)), `fixture ${fixture} must exist`);
    }
    const managed = read("skills/unslopify/tests/fixtures/agents-md/managed.md");
    assert.ok(managed.includes("<!-- managed: document-for-agents"), "managed fixture must carry the marker");
    assert.equal(managed.includes("unslopify:session-start"), false, "managed fixture starts without the owned block");
    const stale = read("skills/unslopify/tests/fixtures/agents-md/stale.md");
    assert.ok(stale.includes("<!-- unslopify:session-start:start -->"), "stale fixture must carry the owned markers");
    assert.equal(stale.includes(SESSION_BLOCK), false, "stale fixture body must differ from the current block");
    const dup = read("skills/unslopify/tests/fixtures/agents-md/duplicate.md");
    assert.equal((dup.match(/unslopify:session-start:start/g) || []).length, 2, "duplicate fixture must carry two blocks");
    const unmatched = read("skills/unslopify/tests/fixtures/agents-md/unmatched.md");
    assert.ok(
      unmatched.includes("<!-- unslopify:session-start:start -->") && !unmatched.includes("<!-- unslopify:session-start:end -->"),
      "unmatched fixture must lack the end marker",
    );
  });

  test("the documented setup rules encode to one deterministic byte-level editor", () => {
    const n = norm(read("skills/unslopify/SKILL.md"));
    for (const rule of ["create root `agents.md`", "directly after", "byte zero", "make no write", "replace only its body", "make no edit", "no partial edit"]) {
      assert.ok(n.includes(rule), `SKILL.md must state the setup rule that maps to ${rule}`);
    }
  });

  test("setup inserts exactly one owned block after the management marker in a managed AGENTS.md", () => {
    const original = read("skills/unslopify/tests/fixtures/agents-md/managed.md");
    const edited = applySetup(original);
    assert.equal(countBlocks(edited), 1, "exactly one owned block after setup");
    assert.ok(edited.includes(SESSION_BLOCK), "the current block body must be present");
    const marker = "<!-- managed: document-for-agents";
    assert.ok(edited.indexOf(SESSION_BLOCK) > edited.indexOf(marker), "the block must sit after the management marker");
    const prefix = edited.slice(0, edited.indexOf(SESSION_BLOCK));
    assert.ok(prefix.includes("1. Say the task goal.") && prefix.includes("<!-- managed: document-for-agents"), "the five commands and marker stay before the block");
    const strip = (s: string) => s.replace(/<!-- unslopify:session-start:start -->[\s\S]*?<!-- unslopify:session-start:end -->/g, "");
    assert.equal(strip(edited), strip(original), "bytes outside the owned block are preserved byte for byte");
  });

  test("setup inserts at byte zero for a bare file, after frontmatter otherwise, and is a byte-identical no-op on repeat", () => {
    const ordinary = read("skills/unslopify/tests/fixtures/agents-md/ordinary.md");
    const first = applySetup(ordinary);
    assert.ok(first.startsWith(SESSION_BLOCK + "\n"), "a file with no frontmatter receives the block at byte zero");
    const frontmatter = read("skills/unslopify/tests/fixtures/agents-md/frontmatter.md");
    const fm = applySetup(frontmatter);
    const fmBody = frontmatter.match(/^---\n[\s\S]*?\n---\n/)?.[0] ?? "";
    assert.ok(fm.startsWith(fmBody), "valid frontmatter stays at the top");
    assert.ok(fm.slice(fmBody.length).startsWith(SESSION_BLOCK), "the block lands directly after frontmatter");
    const again = applySetup(fm);
    assert.equal(again, fm, "a repeated setup on an installed block must be byte-identical");
    const twice = applySetup(first);
    assert.equal(twice, first, "a repeated setup on a byte-zero install must be byte-identical");
  });

  test("setup replaces only a stale block's body and leaves surrounding bytes untouched", () => {
    const stale = read("skills/unslopify/tests/fixtures/agents-md/stale.md");
    const edited = applySetup(stale);
    assert.equal(countBlocks(edited), 1, "one owned block after repair");
    assert.ok(edited.includes(SESSION_BLOCK), "the stale body must be replaced by the current block");
    const strip = (s: string) => s.replace(/<!-- unslopify:session-start:start -->[\s\S]*?<!-- unslopify:session-start:end -->/g, "");
    assert.equal(strip(edited), strip(stale), "bytes outside the owned block are preserved byte for byte");
    assert.equal(edited.includes("Load `unslopify` when documentation cleanup work appears."), false, "the stale body text must be gone");
  });

  test("setup makes no edit and no partial write for duplicate, unmatched, or protected AGENTS.md files", () => {
    const duplicate = read("skills/unslopify/tests/fixtures/agents-md/duplicate.md");
    const unmatched = read("skills/unslopify/tests/fixtures/agents-md/unmatched.md");
    const protected_ = read("skills/unslopify/tests/fixtures/agents-md/protected.md");
    assert.equal(applySetup(duplicate), duplicate, "duplicate markers stop the edit with the file unchanged");
    assert.equal(applySetup(unmatched), unmatched, "unmatched markers stop the edit with the file unchanged");
    assert.equal(applySetup(protected_), protected_, "an externally generated file is left untouched");
  });

  test("absent, managed, frontmatter, stale, and protected edits each change only the owned bytes", () => {
    const cases = [
      "ordinary.md",
      "managed.md",
      "frontmatter.md",
      "stale.md",
      "protected.md",
      "duplicate.md",
      "unmatched.md",
    ] as const;
    const strip = (s: string) => s.replace(/<!-- unslopify:session-start:start -->[\s\S]*?<!-- unslopify:session-start:end -->/g, "");
    for (const fixture of cases) {
      const original = read(`skills/unslopify/tests/fixtures/agents-md/${fixture}`);
      const edited = applySetup(original);
      if (fixture === "protected.md" || fixture === "duplicate.md" || fixture === "unmatched.md") {
        assert.equal(edited, original, `${fixture}: no-edit case must stay byte-identical`);
        continue;
      }
      const outside = fixture === "ordinary.md" ? strip(edited).replace(/^\n\n/, "") : strip(edited);
      assert.equal(outside, strip(original), `${fixture}: bytes outside the owned block must be identical before and after`);
      assert.equal(countBlocks(edited), 1, `${fixture}: exactly one owned block after setup`);
    }
  });

  test("a real temp-file write is byte-identical on repeat and preserves hashes outside the block", () => {
    const cases = [
      "ordinary.md",
      "managed.md",
      "frontmatter.md",
      "stale.md",
      "protected.md",
      "duplicate.md",
      "unmatched.md",
    ] as const;
    const strip = (s: string) => s.replace(/<!-- unslopify:session-start:start -->[\s\S]*?<!-- unslopify:session-start:end -->/g, "");
    const sha = (s: string) => crypto.createHash("sha256").update(s).digest("hex");
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "unslopify-setup-hash-"));
    try {
      for (const fixture of cases) {
        const original = read(`skills/unslopify/tests/fixtures/agents-md/${fixture}`);
        const file = path.join(dir, fixture);
        fs.writeFileSync(file, original);
        const applied = applySetup(fs.readFileSync(file, "utf8"));
        fs.writeFileSync(file, applied);
        const second = applySetup(fs.readFileSync(file, "utf8"));
        assert.equal(sha(second), sha(fs.readFileSync(file, "utf8")), `${fixture}: a repeat run over the installed file must be byte-identical`);
        fs.writeFileSync(file, second);
        if (fixture === "protected.md" || fixture === "duplicate.md" || fixture === "unmatched.md") {
          assert.equal(sha(fs.readFileSync(file, "utf8")), sha(original), `${fixture}: no-edit case must keep the original bytes`);
          continue;
        }
        const onDisk = strip(fs.readFileSync(file, "utf8"));
        const onDiskOutside = fixture === "ordinary.md" ? onDisk.replace(/^\n\n/, "") : onDisk;
        assert.equal(sha(onDiskOutside), sha(strip(original)), `${fixture}: only the owned block bytes may differ from the original`);
        assert.equal(countBlocks(fs.readFileSync(file, "utf8")), 1, `${fixture}: exactly one owned block on disk`);
      }
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  test("leaf doc declares INV-8 with the setup and plain-language contract", () => {
    const leaf = read("docs/leaves/unslopify.md");
    assert.ok(leaf.includes("INV-8"), "leaf must declare INV-8");
    assert.ok(norm(leaf).includes("session-start"), "INV-8 must name the session-start setup");
  });

  test("the setup and phrase decisions are recorded in one accepted ADR that narrows ADR-0015", () => {
    const adr = path.join(ROOT, "docs/adr/0029-unslopify-session-start-and-plain-language-live-output.md");
    assert.ok(fs.existsSync(adr), "ADR-0029 must exist");
    const n = norm(read("docs/adr/0029-unslopify-session-start-and-plain-language-live-output.md"));
    assert.ok(/status:\s*accepted/.test(n), "ADR-0029 must be accepted");
    assert.ok(n.includes("narrows: 0015"), "ADR-0029 must narrow ADR-0015");
    assert.ok(n.includes("session-start"), "ADR-0029 must record the session-start setup");
    assert.ok(n.includes("narrow exception"), "ADR-0029 must record the narrow root-file scope exception");
    assert.ok(n.includes("plain language"), "ADR-0029 must record the plain-language live output");
    assert.ok(n.includes("load-bearing"), "ADR-0029 must record the load-bearing change");
    assert.ok(
      fs.readFileSync(path.join(ROOT, "docs/manifest.md"), "utf8").includes("0029-unslopify-session-start-and-plain-language-live-output.md"),
      "manifest must list ADR-0029",
    );
  });
});
