#!/usr/bin/env node
// Bundled workflow-state validator for the four workflow commands
// (plan-this, implement-this, review-this, fix-this; ADR-0038).
//
// Authored at scripts/workflow-cli.mjs and generated byte-identical into each
// skill package next to its workflow-state.ts copy, so every stage executes
// the same read-only checks against its own installed bundle. No repository
// dependencies, no network, no filesystem writes, no execution of issue or
// review text.
//
// Usage:
//   node workflow-cli.mjs <operation> <input.json>   (input file)
//   node workflow-cli.mjs <operation> -              (JSON on stdin)
//
// Operations (read-only validators over raw bodies plus separately observed
// native facts; each prints one JSON result on stdout and diagnostics on
// stderr):
//   planning     strict canonical publication gate for one body
//   requirements requirements revision, resolution, and coverage over a pair
//   evidence     evidence-v2 handoff validation against current requirements
//   review       review-handoff-v1 validation against recomputed revisions
//   fix-progress fix-progress checkpoint parse and reconciliation
//
// Every operation reads one JSON object. `version` is accepted when present
// and must be 1. Required fields must exist with the documented type; a
// missing or wrong-type field is an input failure (exit 2), never a pass.
//
// Exit codes: 0 valid input and accepted contract; 1 contract rejection
// (valid input that the workflow must stop on); 2 input or runtime failure
// (unknown operation, unreadable input, missing or unsupported runtime,
// missing or wrong-type required fields, internal error).
//
// Verification claims are never accepted from the payload alone. The
// `evidence` and `review` operations extract the success claims the artifact
// makes (passing behavior commands, the review verification command) and the
// failure observations its findings record, then require recorded execution
// receipts and the observed project configuration:
//   configuredCommands   commands the checked-in project configuration
//                        establishes (observed separately)
//   executionReceipts    [{ command, output, exitStatus }] recorded when the
//                        commands actually ran
// A passing claim needs a receipt with the same command and exit status 0;
// a failure observation needs a receipt with the same command and a non-zero
// exit status. Claims without receipts, receipts without recorded output, or
// passing claims whose command is not in the configuration stop the workflow
// (exit 1). Commands inside artifact text are never executed.
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const REQUIRED_NODE_MAJOR = 24;
const HASH = (text) => createHash("sha256").update(text, "utf8").digest("hex");

const CORE_FILE = "workflow-state.ts";

function exitWith(exitCode, result) {
  process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
  process.exit(exitCode);
}

function inputFailure(message) {
  return { ok: false, kind: "input-failure", errors: [message] };
}

function contractRejection(operation, reason, detail) {
  return { ok: false, operation, kind: "contract-rejection", reason, detail };
}

/** Missing or wrong-type required string fields, in order. */
function missingStringFields(record, labels) {
  const missing = [];
  for (const label of labels) {
    if (typeof record[label] !== "string" || record[label].trim() === "") {
      missing.push(label);
    }
  }
  return missing;
}

/** Optional string field: present must be a non-empty string. */
function optionalStringError(record, label, description) {
  if (record[label] !== undefined && (typeof record[label] !== "string" || record[label].trim() === "")) {
    return `${description} must be a string when present`;
  }
  return null;
}

/** Optional boolean field: present must be a boolean. */
function optionalBooleanError(record, label, description) {
  if (record[label] !== undefined && typeof record[label] !== "boolean") {
    return `${description} must be a boolean when present`;
  }
  return null;
}

/** Optional array of non-empty strings. */
function optionalStringArrayError(record, label, description) {
  const value = record[label];
  if (value !== undefined && (!Array.isArray(value) || value.some((entry) => typeof entry !== "string" || entry.trim() === ""))) {
    return `${description} must be an array of non-empty strings when present`;
  }
  return null;
}

/** Optional array of { command, output, exitStatus } execution receipts. */
function executionReceiptError(record) {
  const receipts = record.executionReceipts;
  if (receipts === undefined) return null;
  if (!Array.isArray(receipts)) return "executionReceipts must be an array when present";
  for (const receipt of receipts) {
    if (receipt === null || typeof receipt !== "object") {
      return "each execution receipt must be one object";
    }
    if (typeof receipt.command !== "string" || receipt.command.trim() === "") {
      return "each execution receipt needs a non-empty command";
    }
    if (typeof receipt.output !== "string" || receipt.output.trim() === "") {
      return `execution receipt for \`${typeof receipt.command === "string" ? receipt.command : ""}\` needs recorded output`;
    }
    if (!Number.isInteger(receipt.exitStatus)) {
      return `execution receipt for \`${typeof receipt.command === "string" ? receipt.command : ""}\` needs an integer exit status`;
    }
  }
  return null;
}

/** Integer PR number field. Returns null when valid, else an error message. */
function prNumberError(record) {
  const raw = record.prNumber;
  if (typeof raw !== "number" || !Number.isInteger(raw) || raw < 1) {
    return "prNumber must be a positive integer";
  }
  return null;
}

/**
 * Machine checks for the claims an artifact makes (ADR-0038). Passing claims
 * require the observed project configuration plus a receipt with exit status
 * 0; failure observations require only a recorded receipt with a non-zero
 * exit status. Never executes anything.
 */
function verifyExecutionClaims(record, passClaims, failureClaims) {
  const allClaims = [...passClaims, ...failureClaims];
  if (allClaims.length === 0) {
    return { ok: true, claims: allClaims, errors: [] };
  }
  const errors = [];
  if (passClaims.length > 0) {
    if (!Array.isArray(record.configuredCommands) || record.configuredCommands.length === 0) {
      errors.push("passing verification claims require the separately observed project configuration (configuredCommands)");
    }
    for (const claim of passClaims) {
      if (!Array.isArray(record.configuredCommands) || !record.configuredCommands.includes(claim.command)) {
        errors.push(`claim \`${claim.command}\` (${claim.label}) is not established by the observed project configuration`);
      }
    }
  }
  if (!Array.isArray(record.executionReceipts)) {
    errors.push("verification claims require recorded execution receipts (executionReceipts with command, output, and exitStatus)");
  }
  const byCommand = new Map();
  if (Array.isArray(record.executionReceipts)) {
    for (const receipt of record.executionReceipts) {
      if (!byCommand.has(receipt.command)) byCommand.set(receipt.command, []);
      byCommand.get(receipt.command).push(receipt);
    }
  }
  for (const claim of allClaims) {
    const receipts = byCommand.get(claim.command) ?? [];
    if (receipts.length === 0) {
      errors.push(`no execution receipt recorded for \`${claim.command}\` (${claim.label})`);
      continue;
    }
    const pass = passClaims.includes(claim);
    const match = receipts[0];
    if (pass && match.exitStatus !== 0) {
      errors.push(`receipt for \`${claim.command}\` (${claim.label}) records exit status ${match.exitStatus}; a passing claim requires 0`);
    }
    if (!pass && match.exitStatus === 0) {
      errors.push(`receipt for \`${claim.command}\` (${claim.label}) records exit status 0; failure evidence requires a non-zero status`);
    }
  }
  return { ok: errors.length === 0, claims: allClaims, errors };
}

function claimRejection(operation, claims, errors, passClaims, failureClaims) {
  const failingPass = passClaims.map((claim) => claim.command);
  const failingFailure = failureClaims.map((claim) => claim.command);
  return {
    exit: 1,
    result: {
      ok: false,
      operation,
      kind: "contract-rejection",
      reason: "verification claims must be backed by recorded execution receipts checked against the observed project configuration",
      detail: errors,
      verification: {
        passClaims: failingPass,
        failureObservations: failingFailure,
      },
      diagnostics: {
        message: "the artifact claims verification the run did not record and the configuration does not establish; re-run the commands and record receipts before treating the artifact as current",
      },
    },
  };
}

async function loadCore() {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const coreUrl = pathToFileURL(path.join(here, CORE_FILE));
  return import(coreUrl.href);
}

function parseInput(raw) {
  try {
    const parsed = JSON.parse(raw);
    if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
      throw new Error("input must be one JSON object");
    }
    return { ok: true, value: parsed };
  } catch (error) {
    return { ok: false, error: `input JSON is invalid: ${error.message}` };
  }
}
function operationPlanning(core, record) {
  const missing = missingStringFields(record, ["role", "body"]);
  if (missing.length > 0) {
    return { exit: 2, result: inputFailure(`planning is missing required input: ${missing.join(", ")}`) };
  }
  const role = record.role;
  if (role !== "parent" && role !== "ticket") {
    return { exit: 1, result: contractRejection("planning", "invalid role", "role must be parent or ticket") };
  }
  const body = record.body;
  const canonicalErrors = core.validateAuthoritativeBody(body, role);
  const resolution = core.resolveRequirementsBody(body, role);
  const errors = [...canonicalErrors];
  if (!resolution.ok) {
    for (const error of resolution.errors) {
      if (!errors.includes(error)) errors.push(error);
    }
  }
  const result = {
    ok: canonicalErrors.length === 0 && resolution.ok,
    operation: "planning",
    kind: canonicalErrors.length === 0 && resolution.ok ? "accepted" : "contract-rejection",
    role,
    canonical: canonicalErrors.length === 0,
    format: resolution.format,
    resolutionOk: resolution.ok,
    criteria: resolution.criteria,
    errors,
    notes: resolution.notes,
    diagnostics: {
      publishable: canonicalErrors.length === 0,
      consumable: resolution.ok,
      message: canonicalErrors.length === 0 && resolution.ok
        ? "body passes the canonical publication gate and the consumption resolver"
        : "body fails the canonical publication gate or the consumption resolver",
    },
  };
  return { exit: result.ok ? 0 : 1, result };
}

function revisionDetail(core, parentBody, ticketBody, pinned) {
  let revision = null;
  let coverage = null;
  try {
    revision = core.requirementsRevision(parentBody, ticketBody, HASH);
  } catch (error) {
    if (error && error.name === "RequirementsResolutionError") {
      return {
        revision: null,
        coverage: null,
        resolutionError: error.diagnostics.map((d) => ({ role: d.role, errors: [...d.errors] })),
      };
    }
    throw error;
  }
  const carrier = core.requirementsRevisionValue(revision);
  const parentResolution = core.resolveRequirementsBody(parentBody, "parent");
  const ticketResolution = core.resolveRequirementsBody(ticketBody, "ticket");
  const parentIds = parentResolution.criteria
    .filter((c) => c.status === "active")
    .map((c) => c.id);
  const ticketIds = ticketResolution.criteria
    .filter((c) => c.status === "active")
    .map((c) => c.id);
  coverage = {
    parentActiveCriteria: parentIds,
    ticketActiveCriteria: ticketIds,
    parentCoverage: core.criterionCoverage(
      parentResolution.criteria,
      parentResolution.criteria.filter((c) => c.status === "active").map((c) => c.id),
    ),
    ticketCoverage: core.criterionCoverage(
      ticketResolution.criteria,
      ticketResolution.criteria.filter((c) => c.status === "active").map((c) => c.id),
    ),
  };
  let pinMatch = null;
  if (typeof pinned === "string" && pinned.trim() !== "") {
    pinMatch = {
      pinned,
      current: carrier,
      equal: core.requirementsMatch(pinned, carrier),
      classification:
        pinned === carrier
          ? "current"
          : "mismatch-with-unproven-cause: pin inequality alone never proves a requirements edit; reconcile bodies and proof before repinning (ADR-0038)",
    };
  }
  return { revision, coverage, pinMatch };
}

function operationRequirements(core, record) {
  const missing = missingStringFields(record, ["parentBody", "ticketBody"]);
  if (missing.length > 0) {
    return { exit: 2, result: inputFailure(`requirements is missing required input: ${missing.join(", ")}`) };
  }
  const pinnedError = optionalStringError(record, "pinnedRevision", "pinnedRevision");
  if (pinnedError !== null) {
    return { exit: 2, result: inputFailure(pinnedError) };
  }
  const parentBody = record.parentBody;
  const ticketBody = record.ticketBody;
  const detail = revisionDetail(core, parentBody, ticketBody, record.pinnedRevision);
  if (detail.resolutionError) {
    return {
      exit: 1,
      result: {
        ok: false,
        operation: "requirements",
        kind: "contract-rejection",
        reason: "requirements resolution failed; no requirements revision is emitted for unresolved bodies",
        detail: detail.resolutionError,
      },
    };
  }
  const carrier = core.requirementsRevisionValue(detail.revision);
  const pinOk = detail.pinMatch === null || detail.pinMatch.equal === true;
  const result = {
    ok: pinOk,
    operation: "requirements",
    kind: pinOk ? "accepted" : "contract-rejection",
    version: detail.revision.version,
    parentRevision: detail.revision.parent,
    ticketRevision: detail.revision.ticket,
    revisionCarrier: carrier,
    coverage: detail.coverage,
    pinMatch: detail.pinMatch,
    diagnostics: {
      message: detail.pinMatch === null
        ? "requirements revision computed from the current bodies"
        : detail.pinMatch.equal
          ? "pinned revision matches the current bodies"
          : "pinned revision does not match the current bodies; cause unproven",
    },
  };
  return { exit: pinOk ? 0 : 1, result };
}

function evidenceCriterionIds(core, pullRequestBody) {
  const parsed = core.parseEvidenceHandoff(pullRequestBody);
  if (!parsed.found) return null;
  const normalized = pullRequestBody.replace(/\r\n?/g, "\n");
  const inner = (() => {
    const start = "<!-- ruralnative:compact-evidence:start -->";
    const end = "<!-- ruralnative:compact-evidence:end -->";
    const begin = normalized.indexOf(start);
    if (begin < 0) return "";
    const rest = normalized.slice(begin + start.length);
    const finish = rest.indexOf(end);
    return finish < 0 ? "" : rest.slice(0, finish);
  })();
  const ids = [];
  const pattern = /\*\*Criterion:\*\*\s*`?([A-Za-z]{2,3}-\d+)`?/g;
  let match = null;
  while ((match = pattern.exec(inner)) !== null) ids.push(match[1]);
  return ids;
}

function operationEvidence(core, record) {
  const missing = missingStringFields(record, ["pullRequestBody", "parentBody", "ticketBody", "headSha"]);
  if (missing.length > 0) {
    return { exit: 2, result: inputFailure(`evidence is missing required input: ${missing.join(", ")}`) };
  }
  const legacyError = optionalBooleanError(record, "legacyProvenance", "legacyProvenance");
  const configuredError = optionalStringArrayError(record, "configuredCommands", "configuredCommands");
  const receiptsError = executionReceiptError(record);
  const firstInputError = legacyError ?? configuredError ?? receiptsError;
  if (firstInputError !== null) {
    return { exit: 2, result: inputFailure(firstInputError) };
  }
  const pullRequestBody = record.pullRequestBody;
  const parentBody = record.parentBody;
  const ticketBody = record.ticketBody;
  const headSha = record.headSha;
  const detail = revisionDetail(core, parentBody, ticketBody, null);
  if (detail.resolutionError) {
    return {
      exit: 2,
      result: inputFailure("requirements resolution failed; evidence cannot be validated against unresolved bodies"),
    };
  }
  const currentCarrier = core.requirementsRevisionValue(detail.revision);
  const validation = core.validateEvidenceHandoff({
    body: pullRequestBody,
    currentRequirementsRevision: currentCarrier,
    currentHeadSha: headSha,
    legacyProvenance: record.legacyProvenance === true,
  });
  const proofIds = evidenceCriterionIds(core, pullRequestBody) ?? [];
  const ticketResolution = core.resolveRequirementsBody(ticketBody, "ticket");
  const coverage = core.criterionCoverage(ticketResolution.criteria, proofIds);
  const coverageOk =
    coverage.missing.length === 0 && coverage.extra.length === 0 && coverage.duplicates.length === 0;
  let verifiedClaims = null;
  if (validation.status === "current" && coverageOk) {
    const behaviorClaims = core
      .extractEvidenceBehaviorClaims(pullRequestBody)
      .map((c) => ({ label: `criterion ${c.criterionId}`, command: c.command }));
    const verified = verifyExecutionClaims(record, behaviorClaims, []);
    if (!verified.ok) {
      return claimRejection("evidence", verified.claims, verified.errors, behaviorClaims, []);
    }
    verifiedClaims = verified.claims.map((c) => c.command);
  }
  const result = {
    ok: validation.status === "current" && coverageOk,
    operation: "evidence",
    kind: validation.status === "current" && coverageOk ? "accepted" : "contract-rejection",
    status: validation.status,
    reason: validation.reason,
    currentRequirementsRevision: currentCarrier,
    coverage,
    verificationClaims: verifiedClaims,
    diagnostics: {
      message: validation.status === "current" && coverageOk
        ? "evidence validates current and covers every resolved active ticket criterion"
        : "evidence is not ready for review; reconcile implementation evidence outside review",
    },
  };
  return { exit: result.ok ? 0 : 1, result };
}

function operationReview(core, record) {
  const missing = missingStringFields(record, ["reviewBody", "repository", "headSha", "baseSha", "parentBody", "ticketBody"]);
  if (missing.length > 0) {
    return { exit: 2, result: inputFailure(`review is missing required input: ${missing.join(", ")}`) };
  }
  const prError = prNumberError(record);
  const configuredError = optionalStringArrayError(record, "configuredCommands", "configuredCommands");
  const receiptsError = executionReceiptError(record);
  const completedError = optionalBooleanError(record, "reviewCompleted", "reviewCompleted");
  const dismissedError = optionalBooleanError(record, "reviewDismissed", "reviewDismissed");
  const firstInputError = prError ?? configuredError ?? receiptsError ?? completedError ?? dismissedError;
  if (firstInputError !== null) {
    return { exit: 2, result: inputFailure(firstInputError) };
  }
  const reviewBody = record.reviewBody;
  const repository = record.repository;
  const prNumber = record.prNumber;
  const headSha = record.headSha;
  const baseSha = record.baseSha;
  const parentBody = record.parentBody;
  const ticketBody = record.ticketBody;
  const detail = revisionDetail(core, parentBody, ticketBody, null);
  if (detail.resolutionError) {
    return {
      exit: 2,
      result: inputFailure("requirements resolution failed; the review handoff cannot be validated against unresolved bodies"),
    };
  }
  const requirementsRevision = core.requirementsRevisionValue(detail.revision);
  const sources = Array.isArray(record.policySources) ? record.policySources : [];
  const policyRevision = core.effectivePolicyRevision(
    sources.map((source) => ({
      path: String(source.path ?? ""),
      hash: String(source.hash ?? ""),
    })),
  );
  const observed = record.observedProvenance ?? null;
  if (observed === null || typeof observed !== "object" || Array.isArray(observed)) {
    return {
      exit: 2,
      result: inputFailure("review requires an observedProvenance object with the observed native review facts"),
    };
  }
  const provenanceIdError =
    optionalStringError({ reviewId: observed.reviewId }, "reviewId", "observedProvenance.reviewId") ??
    optionalStringError({ reviewAuthor: observed.reviewAuthor }, "reviewAuthor", "observedProvenance.reviewAuthor") ??
    optionalStringError({ reviewerPermission: observed.reviewerPermission }, "reviewerPermission", "observedProvenance.reviewerPermission") ??
    optionalStringError({ reviewedCommit: observed.reviewedCommit }, "reviewedCommit", "observedProvenance.reviewedCommit");
  if (provenanceIdError !== null) {
    return { exit: 2, result: inputFailure(provenanceIdError) };
  }
  if (observed.reviewedAt !== undefined && typeof observed.reviewedAt !== "string") {
    return { exit: 2, result: inputFailure("observedProvenance.reviewedAt must be a string when present") };
  }
  if (observed.sourceUrl !== undefined && typeof observed.sourceUrl !== "string") {
    return { exit: 2, result: inputFailure("observedProvenance.sourceUrl must be a string when present") };
  }
  if (
    observed.commentIds !== undefined &&
    (!Array.isArray(observed.commentIds) || observed.commentIds.some((id) => typeof id !== "string"))
  ) {
    return { exit: 2, result: inputFailure("observedProvenance.commentIds must be an array of strings when present") };
  }
  const completed = record.reviewCompleted === true;
  const dismissed = record.reviewDismissed === true;
  const validation = core.validateReviewHandoff({
    body: reviewBody,
    repository,
    prNumber,
    currentHeadSha: headSha,
    currentBaseSha: baseSha,
    currentRequirementsRevision: requirementsRevision,
    currentReviewPolicyRevision: policyRevision,
    observedProvenance: {
      reviewId: String(observed.reviewId ?? ""),
      reviewAuthor: String(observed.reviewAuthor ?? ""),
      reviewerPermission: String(observed.reviewerPermission ?? "unknown"),
      reviewedCommit: String(observed.reviewedCommit ?? ""),
      reviewedAt: typeof observed.reviewedAt === "string" ? observed.reviewedAt : undefined,
      sourceUrl: typeof observed.sourceUrl === "string" ? observed.sourceUrl : undefined,
      commentIds: Array.isArray(observed.commentIds)
        ? observed.commentIds.map((id) => String(id))
        : [],
    },
    reviewCompleted: completed,
    reviewDismissed: dismissed,
  });
  let verifiedClaims = null;
  if (validation.status === "current" && validation.handoff) {
    const passClaims = [];
    if (validation.handoff.verificationPassed === true) {
      passClaims.push({ label: "review verification", command: validation.handoff.verificationCommand });
    }
    const failureClaims = validation.handoff.findings
      .filter((finding) => finding.evidenceKind === "failure" && finding.command)
      .map((finding) => ({ label: `finding ${finding.id}`, command: finding.command }));
    const verified = verifyExecutionClaims(record, passClaims, failureClaims);
    if (!verified.ok) {
      return claimRejection("review", verified.claims, verified.errors, passClaims, failureClaims);
    }
    verifiedClaims = verified.claims.map((c) => c.command);
  }
  const result = {
    ok: validation.status === "current",
    operation: "review",
    kind: validation.status === "current" ? "accepted" : "contract-rejection",
    status: validation.status,
    reason: validation.reason,
    requirementsRevision,
    reviewPolicyRevision: policyRevision,
    verificationClaims: verifiedClaims,
    diagnostics: {
      message:
        validation.status === "current"
          ? "review handoff validates current for the recomputed revisions"
          : "review handoff is not current; republish the review on the current revisions",
    },
  };
  return { exit: result.ok ? 0 : 1, result };
}

function operationFixProgress(core, record) {
  const missing = missingStringFields(record, ["body", "repository"]);
  if (missing.length > 0) {
    return { exit: 2, result: inputFailure(`fix-progress is missing required input: ${missing.join(", ")}`) };
  }
  const prError = prNumberError(record);
  const sourceError = optionalStringError(record, "sourceHandoffBody", "sourceHandoffBody");
  if (prError !== null || sourceError !== null) {
    return { exit: 2, result: inputFailure(prError ?? sourceError ?? "") };
  }
  const body = record.body;
  const repository = record.repository;
  const prNumber = record.prNumber;
  const parsed = core.parseFixProgress({ body, repository, prNumber });
  if (!parsed.found) {
    const result = {
      ok: false,
      operation: "fix-progress",
      kind: parsed.malformed ? "contract-rejection" : "accepted",
      found: false,
      reason: parsed.reason,
      diagnostics: {
        message: parsed.malformed
          ? "the checkpoint is malformed; legacy or missing progress is diagnostic, never permission to skip work"
          : "no fix progress checkpoint; fresh finalization applies",
      },
    };
    return { exit: parsed.malformed ? 1 : 0, result };
  }
  let reconciliation = null;
  if (parsed.malformed) {
    const result = {
      ok: false,
      operation: "fix-progress",
      kind: "contract-rejection",
      found: true,
      reason: parsed.reason,
      diagnostics: {
        message: "the checkpoint is malformed; it never authorizes work alone",
      },
    };
    return { exit: 1, result };
  }
  if (!parsed.legacy) {
    if (typeof record.sourceHandoffBody !== "string" || record.sourceHandoffBody.trim() === "") {
      return {
        exit: 2,
        result: inputFailure("a fix-progress-v2 checkpoint requires sourceHandoffBody (the validated source review body) for reconciliation"),
      };
    }
    const sourceDigest = core.reviewHandoffDigestOfBody(record.sourceHandoffBody, HASH);
    if (!sourceDigest.ok) {
      return {
        exit: 2,
        result: inputFailure(`sourceHandoffBody is not a readable review handoff: ${sourceDigest.reason}`),
      };
    }
    const sourceParse = core.parseReviewHandoffInput(record.sourceHandoffBody);
    if (!sourceParse.ok) {
      return {
        exit: 2,
        result: inputFailure(`sourceHandoffBody is not a readable review handoff: ${sourceParse.reason}`),
      };
    }
    const source = sourceParse.handoff;
    const digestMatches = sourceDigest.digest === parsed.sourceHandoffDigest;
    const startedHeadMatchesReview = parsed.startedHeadSha === source.reviewedHeadSha;
    const startedBaseMatchesReview = parsed.startedBaseSha === source.reviewedBaseSha;
    const findingIds = new Set(source.findings.map((finding) => finding.id));
    const disposedIds = new Set((parsed.dispositions ?? []).map((d) => d.findingId));
    const missingDispositions = [...findingIds].filter((id) => !disposedIds.has(id)).sort();
    const extraDispositions = (parsed.dispositions ?? [])
      .map((d) => d.findingId)
      .filter((id) => !findingIds.has(id))
      .sort();
    const dispositionsCoverSource =
      missingDispositions.length === 0 && extraDispositions.length === 0;
    reconciliation = {
      sourceHandoffDigestRecomputed: sourceDigest.digest,
      digestMatches,
      startedHeadMatchesReview,
      startedBaseMatchesReview,
      dispositionsCoverSource,
      missingDispositions,
      extraDispositions,
    };
    if (!digestMatches || !startedHeadMatchesReview || !startedBaseMatchesReview || !dispositionsCoverSource) {
      const failures = [];
      if (!digestMatches) {
        failures.push("the checkpoint handoff digest does not match the validated source review; digest mismatch stops resume");
      }
      if (!startedHeadMatchesReview || !startedBaseMatchesReview) {
        failures.push("the checkpoint started revisions do not match the source review's reviewed revisions");
      }
      if (!dispositionsCoverSource) {
        failures.push(
          `the checkpoint dispositions do not cover the source findings exactly${missingDispositions.length > 0 ? ` (missing: ${missingDispositions.join(", ")})` : ""}${extraDispositions.length > 0 ? ` (extra: ${extraDispositions.join(", ")})` : ""}`,
        );
      }
      return {
        exit: 1,
        result: {
          ok: false,
          operation: "fix-progress",
          kind: "contract-rejection",
          found: true,
          reason: failures.join("; "),
          reconciliation,
          diagnostics: {
            message: "the checkpoint does not reconcile against the validated source review; never resume on it",
          },
        },
      };
    }
  }
  const result = {
    ok: true,
    operation: "fix-progress",
    kind: "accepted",
    found: true,
    version: parsed.version ?? null,
    parsed: {
      repository: parsed.repository,
      prNumber: parsed.prNumber,
      sourceReviewId: parsed.sourceReviewId,
      sourceHandoffDigest: parsed.sourceHandoffDigest,
      ticket: parsed.ticket,
      parent: parsed.parent,
      startedHeadSha: parsed.startedHeadSha,
      startedBaseSha: parsed.startedBaseSha,
      resultingHeadSha: parsed.resultingHeadSha,
      resultingBaseSha: parsed.resultingBaseSha,
      dispositions: parsed.dispositions,
      completedSteps: parsed.completedSteps,
      intendedRemoteOperation: parsed.intendedRemoteOperation,
      mergeReceipt: parsed.mergeReceipt,
      verificationReceipts: parsed.verificationReceipts,
    },
    reconciliation,
    reason: parsed.reason,
    diagnostics: {
      message: reconciliation === null
        ? "the checkpoint parsed as legacy diagnostic input; it never authorizes skipping work"
        : "the checkpoint parsed and reconciles against the validated source review; reconcile local and remote state before resuming",
    },
  };
  return { exit: 0, result };
}

async function main() {
  const nodeMajor = Number.parseInt(process.versions.node.split(".")[0], 10);
  if (!Number.isInteger(nodeMajor) || nodeMajor < REQUIRED_NODE_MAJOR) {
    exitWith(
      2,
      inputFailure(
        `this bundled validator requires Node ${REQUIRED_NODE_MAJOR} or newer (found ${process.version}); upgrade the runtime before running workflow checks`,
      ),
    );
  }
  const [operation, inputPath] = process.argv.slice(2);
  const supported = new Set(["planning", "requirements", "evidence", "review", "fix-progress"]);
  if (!supported.has(operation)) {
    exitWith(
      2,
      inputFailure(
        `unknown operation \`${operation ?? ""}\`; supported operations: ${[...supported].join(", ")}`,
      ),
    );
  }
  if (inputPath === undefined) {
    exitWith(2, inputFailure("missing input path; pass <operation> <input.json> or <operation> - for stdin"));
  }
  let raw = "";
  try {
    raw = inputPath === "-" ? await readStdin() : readFileSync(inputPath, "utf8");
  } catch (error) {
    exitWith(2, inputFailure(`input is unreadable: ${error.message}`));
  }
  const parsedInput = parseInput(raw);
  if (!parsedInput.ok) exitWith(2, inputFailure(parsedInput.error));
  if (parsedInput.value.version !== undefined && parsedInput.value.version !== 1 && parsedInput.value.version !== "1") {
    exitWith(
      2,
      inputFailure(`unsupported input schema version ${JSON.stringify(parsedInput.value.version)}; supported version: 1`),
    );
  }
  let core = null;
  try {
    core = await loadCore();
  } catch (error) {
    exitWith(2, inputFailure(`the bundled workflow-state core is unavailable: ${error.message}`));
  }
  let outcome;
  try {
    if (operation === "planning") outcome = operationPlanning(core, parsedInput.value);
    else if (operation === "requirements") outcome = operationRequirements(core, parsedInput.value);
    else if (operation === "evidence") outcome = operationEvidence(core, parsedInput.value);
    else if (operation === "review") outcome = operationReview(core, parsedInput.value);
    else outcome = operationFixProgress(core, parsedInput.value);
  } catch (error) {
    exitWith(2, inputFailure(`workflow check failed internally: ${error.message}`));
  }
  exitWith(outcome.exit, outcome.result);
}

function readStdin() {
  return new Promise((resolve, reject) => {
    const chunks = [];
    process.stdin.on("data", (chunk) => chunks.push(chunk));
    process.stdin.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    process.stdin.on("error", reject);
  });
}

main();
